baseurl = "https://blockpartyomegagames.netlify.com/"
languageCode = "en-us"
title = "Block Party"
theme = "landing-page-hugo"

[params]
    googleAnalytics = "UA-119556789-1"
    description = "A frantic block-matching race against the world"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:ron@omegagames.gg"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/OmegaGamesGG"
[[params.social]]
    title = "facebook"
    icon = "facebook"
    url = "https://www.facebook.com/omegagamesgg/"
[[params.social]]
    title = "instagram"
    icon = "instagram"
    url = "https://www.instagram.com/omegagamesgg/"
